name: Release Cordova Plugin (GitHub)

on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
    ci:
        uses: ./.github/workflows/reusable_ci.yml
        secrets:
          THE_GH_RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
    
    release:
      needs: ['ci']
      runs-on: 'ubuntu-latest'
      timeout-minutes: 20
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            token: ${{ secrets.RELEASE_TOKEN_GITHUB }}
        - name: 'Setup Tools'
          uses: ./.github/actions/setup-tools
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN_GITHUB }}
          run: npx semantic-release
